// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Current sync status
enum SyncStatus: Int {
  case idle = 0
  case pending = 1
  case active = 2
  case failed = 3
}

/// Represents a user account with associated metadata
///
/// Generated class from Pigeon that represents data sent in messages.
struct AccountData {
  var username: String
  var accountType: String
  var displayName: String? = nil
  var userData: [String?: String?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AccountData? {
    let username = pigeonVar_list[0] as! String
    let accountType = pigeonVar_list[1] as! String
    let displayName: String? = nilOrValue(pigeonVar_list[2])
    let userData: [String?: String?]? = nilOrValue(pigeonVar_list[3])

    return AccountData(
      username: username,
      accountType: accountType,
      displayName: displayName,
      userData: userData
    )
  }
  func toList() -> [Any?] {
    return [
      username,
      accountType,
      displayName,
      userData,
    ]
  }
}

/// Statistics from a completed sync operation
///
/// Generated class from Pigeon that represents data sent in messages.
struct SyncStatsData {
  var itemsUploaded: Int64
  var itemsDownloaded: Int64
  var conflicts: Int64
  var syncTimeMs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SyncStatsData? {
    let itemsUploaded = pigeonVar_list[0] as! Int64
    let itemsDownloaded = pigeonVar_list[1] as! Int64
    let conflicts = pigeonVar_list[2] as! Int64
    let syncTimeMs = pigeonVar_list[3] as! Int64

    return SyncStatsData(
      itemsUploaded: itemsUploaded,
      itemsDownloaded: itemsDownloaded,
      conflicts: conflicts,
      syncTimeMs: syncTimeMs
    )
  }
  func toList() -> [Any?] {
    return [
      itemsUploaded,
      itemsDownloaded,
      conflicts,
      syncTimeMs,
    ]
  }
}

/// Result of a sync operation with statistics
///
/// Generated class from Pigeon that represents data sent in messages.
struct SyncResultData {
  var success: Bool
  var errorCode: Int64? = nil
  var errorMessage: String? = nil
  var stats: SyncStatsData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SyncResultData? {
    let success = pigeonVar_list[0] as! Bool
    let errorCode: Int64? = nilOrValue(pigeonVar_list[1])
    let errorMessage: String? = nilOrValue(pigeonVar_list[2])
    let stats: SyncStatsData? = nilOrValue(pigeonVar_list[3])

    return SyncResultData(
      success: success,
      errorCode: errorCode,
      errorMessage: errorMessage,
      stats: stats
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      errorCode,
      errorMessage,
      stats,
    ]
  }
}

/// Configuration for periodic sync scheduling
///
/// Generated class from Pigeon that represents data sent in messages.
struct PeriodicSyncConfig {
  var intervalSeconds: Int64
  var flexSeconds: Int64? = nil
  var requiresNetwork: Bool? = nil
  var requiresCharging: Bool? = nil
  var extras: [String?: String?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PeriodicSyncConfig? {
    let intervalSeconds = pigeonVar_list[0] as! Int64
    let flexSeconds: Int64? = nilOrValue(pigeonVar_list[1])
    let requiresNetwork: Bool? = nilOrValue(pigeonVar_list[2])
    let requiresCharging: Bool? = nilOrValue(pigeonVar_list[3])
    let extras: [String?: String?]? = nilOrValue(pigeonVar_list[4])

    return PeriodicSyncConfig(
      intervalSeconds: intervalSeconds,
      flexSeconds: flexSeconds,
      requiresNetwork: requiresNetwork,
      requiresCharging: requiresCharging,
      extras: extras
    )
  }
  func toList() -> [Any?] {
    return [
      intervalSeconds,
      flexSeconds,
      requiresNetwork,
      requiresCharging,
      extras,
    ]
  }
}

/// Auth token request result
///
/// Generated class from Pigeon that represents data sent in messages.
struct AuthTokenResult {
  var token: String? = nil
  var errorCode: Int64? = nil
  var errorMessage: String? = nil
  var requiresUserInteraction: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AuthTokenResult? {
    let token: String? = nilOrValue(pigeonVar_list[0])
    let errorCode: Int64? = nilOrValue(pigeonVar_list[1])
    let errorMessage: String? = nilOrValue(pigeonVar_list[2])
    let requiresUserInteraction: Bool? = nilOrValue(pigeonVar_list[3])

    return AuthTokenResult(
      token: token,
      errorCode: errorCode,
      errorMessage: errorMessage,
      requiresUserInteraction: requiresUserInteraction
    )
  }
  func toList() -> [Any?] {
    return [
      token,
      errorCode,
      errorMessage,
      requiresUserInteraction,
    ]
  }
}

/// Sync progress update
///
/// Generated class from Pigeon that represents data sent in messages.
struct SyncProgressData {
  var phase: String
  var progress: Double
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SyncProgressData? {
    let phase = pigeonVar_list[0] as! String
    let progress = pigeonVar_list[1] as! Double
    let message: String? = nilOrValue(pigeonVar_list[2])

    return SyncProgressData(
      phase: phase,
      progress: progress,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      phase,
      progress,
      message,
    ]
  }
}

private class AccountManagerApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SyncStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return AccountData.fromList(self.readValue() as! [Any?])
    case 131:
      return SyncStatsData.fromList(self.readValue() as! [Any?])
    case 132:
      return SyncResultData.fromList(self.readValue() as! [Any?])
    case 133:
      return PeriodicSyncConfig.fromList(self.readValue() as! [Any?])
    case 134:
      return AuthTokenResult.fromList(self.readValue() as! [Any?])
    case 135:
      return SyncProgressData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class AccountManagerApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SyncStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? AccountData {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? SyncStatsData {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? SyncResultData {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PeriodicSyncConfig {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? AuthTokenResult {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? SyncProgressData {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class AccountManagerApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return AccountManagerApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return AccountManagerApiPigeonCodecWriter(data: data)
  }
}

class AccountManagerApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = AccountManagerApiPigeonCodec(readerWriter: AccountManagerApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AccountManagerHostApi {
  func addAccount(account: AccountData, password: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func getAccounts(accountType: String, completion: @escaping (Result<[AccountData], Error>) -> Void)
  func getAccount(username: String, accountType: String, completion: @escaping (Result<AccountData?, Error>) -> Void)
  func updateAccount(account: AccountData, completion: @escaping (Result<Bool, Error>) -> Void)
  func removeAccount(account: AccountData, completion: @escaping (Result<Bool, Error>) -> Void)
  func accountExists(username: String, accountType: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func updateCredentials(account: AccountData, newPassword: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func validateCredentials(username: String, password: String, accountType: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func clearCredentials(account: AccountData, completion: @escaping (Result<Bool, Error>) -> Void)
  func getAuthToken(account: AccountData, tokenType: String, completion: @escaping (Result<AuthTokenResult, Error>) -> Void)
  func setAuthToken(account: AccountData, tokenType: String, token: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func invalidateAuthToken(accountType: String, token: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func invalidateAllTokens(account: AccountData, tokenType: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func getAvailableTokenTypes(account: AccountData, completion: @escaping (Result<[String], Error>) -> Void)
  func syncNow(account: AccountData, expedited: Bool, completion: @escaping (Result<SyncResultData, Error>) -> Void)
  func setSyncAutomatically(account: AccountData, enabled: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func isSyncAutomatically(account: AccountData, completion: @escaping (Result<Bool, Error>) -> Void)
  func addPeriodicSync(account: AccountData, config: PeriodicSyncConfig, completion: @escaping (Result<Bool, Error>) -> Void)
  func removePeriodicSync(account: AccountData, completion: @escaping (Result<Bool, Error>) -> Void)
  func getSyncStatus(account: AccountData, completion: @escaping (Result<SyncStatus, Error>) -> Void)
  func cancelSync(account: AccountData, completion: @escaping (Result<Bool, Error>) -> Void)
  func openAccountSettings(completion: @escaping (Result<Bool, Error>) -> Void)
  func isConfigured(completion: @escaping (Result<Bool, Error>) -> Void)
  func getPlatformCapabilities(completion: @escaping (Result<[String: Bool], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AccountManagerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { AccountManagerApiPigeonCodec.shared }
  /// Sets up an instance of `AccountManagerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AccountManagerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let addAccountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.addAccount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addAccountChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        let passwordArg = args[1] as! String
        api.addAccount(account: accountArg, password: passwordArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addAccountChannel.setMessageHandler(nil)
    }
    let getAccountsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.getAccounts\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAccountsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountTypeArg = args[0] as! String
        api.getAccounts(accountType: accountTypeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAccountsChannel.setMessageHandler(nil)
    }
    let getAccountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.getAccount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAccountChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let usernameArg = args[0] as! String
        let accountTypeArg = args[1] as! String
        api.getAccount(username: usernameArg, accountType: accountTypeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAccountChannel.setMessageHandler(nil)
    }
    let updateAccountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.updateAccount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateAccountChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        api.updateAccount(account: accountArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateAccountChannel.setMessageHandler(nil)
    }
    let removeAccountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.removeAccount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeAccountChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        api.removeAccount(account: accountArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      removeAccountChannel.setMessageHandler(nil)
    }
    let accountExistsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.accountExists\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      accountExistsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let usernameArg = args[0] as! String
        let accountTypeArg = args[1] as! String
        api.accountExists(username: usernameArg, accountType: accountTypeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      accountExistsChannel.setMessageHandler(nil)
    }
    let updateCredentialsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.updateCredentials\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateCredentialsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        let newPasswordArg = args[1] as! String
        api.updateCredentials(account: accountArg, newPassword: newPasswordArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateCredentialsChannel.setMessageHandler(nil)
    }
    let validateCredentialsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.validateCredentials\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      validateCredentialsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let usernameArg = args[0] as! String
        let passwordArg = args[1] as! String
        let accountTypeArg = args[2] as! String
        api.validateCredentials(username: usernameArg, password: passwordArg, accountType: accountTypeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      validateCredentialsChannel.setMessageHandler(nil)
    }
    let clearCredentialsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.clearCredentials\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearCredentialsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        api.clearCredentials(account: accountArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearCredentialsChannel.setMessageHandler(nil)
    }
    let getAuthTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.getAuthToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAuthTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        let tokenTypeArg = args[1] as! String
        api.getAuthToken(account: accountArg, tokenType: tokenTypeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAuthTokenChannel.setMessageHandler(nil)
    }
    let setAuthTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.setAuthToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAuthTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        let tokenTypeArg = args[1] as! String
        let tokenArg = args[2] as! String
        api.setAuthToken(account: accountArg, tokenType: tokenTypeArg, token: tokenArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setAuthTokenChannel.setMessageHandler(nil)
    }
    let invalidateAuthTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.invalidateAuthToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      invalidateAuthTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountTypeArg = args[0] as! String
        let tokenArg = args[1] as! String
        api.invalidateAuthToken(accountType: accountTypeArg, token: tokenArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      invalidateAuthTokenChannel.setMessageHandler(nil)
    }
    let invalidateAllTokensChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.invalidateAllTokens\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      invalidateAllTokensChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        let tokenTypeArg = args[1] as! String
        api.invalidateAllTokens(account: accountArg, tokenType: tokenTypeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      invalidateAllTokensChannel.setMessageHandler(nil)
    }
    let getAvailableTokenTypesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.getAvailableTokenTypes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAvailableTokenTypesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        api.getAvailableTokenTypes(account: accountArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAvailableTokenTypesChannel.setMessageHandler(nil)
    }
    let syncNowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.syncNow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      syncNowChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        let expeditedArg = args[1] as! Bool
        api.syncNow(account: accountArg, expedited: expeditedArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      syncNowChannel.setMessageHandler(nil)
    }
    let setSyncAutomaticallyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.setSyncAutomatically\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSyncAutomaticallyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        let enabledArg = args[1] as! Bool
        api.setSyncAutomatically(account: accountArg, enabled: enabledArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setSyncAutomaticallyChannel.setMessageHandler(nil)
    }
    let isSyncAutomaticallyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.isSyncAutomatically\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSyncAutomaticallyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        api.isSyncAutomatically(account: accountArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isSyncAutomaticallyChannel.setMessageHandler(nil)
    }
    let addPeriodicSyncChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.addPeriodicSync\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addPeriodicSyncChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        let configArg = args[1] as! PeriodicSyncConfig
        api.addPeriodicSync(account: accountArg, config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      addPeriodicSyncChannel.setMessageHandler(nil)
    }
    let removePeriodicSyncChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.removePeriodicSync\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removePeriodicSyncChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        api.removePeriodicSync(account: accountArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      removePeriodicSyncChannel.setMessageHandler(nil)
    }
    let getSyncStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.getSyncStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSyncStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        api.getSyncStatus(account: accountArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getSyncStatusChannel.setMessageHandler(nil)
    }
    let cancelSyncChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.cancelSync\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelSyncChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accountArg = args[0] as! AccountData
        api.cancelSync(account: accountArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelSyncChannel.setMessageHandler(nil)
    }
    let openAccountSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.openAccountSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openAccountSettingsChannel.setMessageHandler { _, reply in
        api.openAccountSettings { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openAccountSettingsChannel.setMessageHandler(nil)
    }
    let isConfiguredChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.isConfigured\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isConfiguredChannel.setMessageHandler { _, reply in
        api.isConfigured { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isConfiguredChannel.setMessageHandler(nil)
    }
    let getPlatformCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.account_manager.AccountManagerHostApi.getPlatformCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPlatformCapabilitiesChannel.setMessageHandler { _, reply in
        api.getPlatformCapabilities { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getPlatformCapabilitiesChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol SyncCallbackFlutterApiProtocol {
  func onSyncStarted(account accountArg: AccountData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onSyncProgress(account accountArg: AccountData, progress progressArg: SyncProgressData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onSyncCompleted(account accountArg: AccountData, result resultArg: SyncResultData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onSyncCancelled(account accountArg: AccountData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onSyncConflict(account accountArg: AccountData, conflictId conflictIdArg: String, localData localDataArg: String, remoteData remoteDataArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class SyncCallbackFlutterApi: SyncCallbackFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: AccountManagerApiPigeonCodec {
    return AccountManagerApiPigeonCodec.shared
  }
  func onSyncStarted(account accountArg: AccountData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.account_manager.SyncCallbackFlutterApi.onSyncStarted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([accountArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onSyncProgress(account accountArg: AccountData, progress progressArg: SyncProgressData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.account_manager.SyncCallbackFlutterApi.onSyncProgress\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([accountArg, progressArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onSyncCompleted(account accountArg: AccountData, result resultArg: SyncResultData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.account_manager.SyncCallbackFlutterApi.onSyncCompleted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([accountArg, resultArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onSyncCancelled(account accountArg: AccountData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.account_manager.SyncCallbackFlutterApi.onSyncCancelled\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([accountArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onSyncConflict(account accountArg: AccountData, conflictId conflictIdArg: String, localData localDataArg: String, remoteData remoteDataArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.account_manager.SyncCallbackFlutterApi.onSyncConflict\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([accountArg, conflictIdArg, localDataArg, remoteDataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol AccountCallbackFlutterApiProtocol {
  func onAccountAdded(account accountArg: AccountData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAccountRemoved(account accountArg: AccountData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAccountUpdated(account accountArg: AccountData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAuthTokenExpired(account accountArg: AccountData, tokenType tokenTypeArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class AccountCallbackFlutterApi: AccountCallbackFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: AccountManagerApiPigeonCodec {
    return AccountManagerApiPigeonCodec.shared
  }
  func onAccountAdded(account accountArg: AccountData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.account_manager.AccountCallbackFlutterApi.onAccountAdded\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([accountArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onAccountRemoved(account accountArg: AccountData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.account_manager.AccountCallbackFlutterApi.onAccountRemoved\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([accountArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onAccountUpdated(account accountArg: AccountData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.account_manager.AccountCallbackFlutterApi.onAccountUpdated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([accountArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onAuthTokenExpired(account accountArg: AccountData, tokenType tokenTypeArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.account_manager.AccountCallbackFlutterApi.onAuthTokenExpired\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([accountArg, tokenTypeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
