// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.lkrjangid.account_manager

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Current sync status */
enum class SyncStatus(val raw: Int) {
  IDLE(0),
  PENDING(1),
  ACTIVE(2),
  FAILED(3);

  companion object {
    fun ofRaw(raw: Int): SyncStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Represents a user account with associated metadata
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AccountData (
  val username: String,
  val accountType: String,
  val displayName: String? = null,
  val userData: Map<String?, String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AccountData {
      val username = pigeonVar_list[0] as String
      val accountType = pigeonVar_list[1] as String
      val displayName = pigeonVar_list[2] as String?
      val userData = pigeonVar_list[3] as Map<String?, String?>?
      return AccountData(username, accountType, displayName, userData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      username,
      accountType,
      displayName,
      userData,
    )
  }
}

/**
 * Statistics from a completed sync operation
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SyncStatsData (
  val itemsUploaded: Long,
  val itemsDownloaded: Long,
  val conflicts: Long,
  val syncTimeMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SyncStatsData {
      val itemsUploaded = pigeonVar_list[0] as Long
      val itemsDownloaded = pigeonVar_list[1] as Long
      val conflicts = pigeonVar_list[2] as Long
      val syncTimeMs = pigeonVar_list[3] as Long
      return SyncStatsData(itemsUploaded, itemsDownloaded, conflicts, syncTimeMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      itemsUploaded,
      itemsDownloaded,
      conflicts,
      syncTimeMs,
    )
  }
}

/**
 * Result of a sync operation with statistics
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SyncResultData (
  val success: Boolean,
  val errorCode: Long? = null,
  val errorMessage: String? = null,
  val stats: SyncStatsData? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SyncResultData {
      val success = pigeonVar_list[0] as Boolean
      val errorCode = pigeonVar_list[1] as Long?
      val errorMessage = pigeonVar_list[2] as String?
      val stats = pigeonVar_list[3] as SyncStatsData?
      return SyncResultData(success, errorCode, errorMessage, stats)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      errorCode,
      errorMessage,
      stats,
    )
  }
}

/**
 * Configuration for periodic sync scheduling
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PeriodicSyncConfig (
  val intervalSeconds: Long,
  val flexSeconds: Long? = null,
  val requiresNetwork: Boolean? = null,
  val requiresCharging: Boolean? = null,
  val extras: Map<String?, String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PeriodicSyncConfig {
      val intervalSeconds = pigeonVar_list[0] as Long
      val flexSeconds = pigeonVar_list[1] as Long?
      val requiresNetwork = pigeonVar_list[2] as Boolean?
      val requiresCharging = pigeonVar_list[3] as Boolean?
      val extras = pigeonVar_list[4] as Map<String?, String?>?
      return PeriodicSyncConfig(intervalSeconds, flexSeconds, requiresNetwork, requiresCharging, extras)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      intervalSeconds,
      flexSeconds,
      requiresNetwork,
      requiresCharging,
      extras,
    )
  }
}

/**
 * Auth token request result
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AuthTokenResult (
  val token: String? = null,
  val errorCode: Long? = null,
  val errorMessage: String? = null,
  val requiresUserInteraction: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AuthTokenResult {
      val token = pigeonVar_list[0] as String?
      val errorCode = pigeonVar_list[1] as Long?
      val errorMessage = pigeonVar_list[2] as String?
      val requiresUserInteraction = pigeonVar_list[3] as Boolean?
      return AuthTokenResult(token, errorCode, errorMessage, requiresUserInteraction)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      token,
      errorCode,
      errorMessage,
      requiresUserInteraction,
    )
  }
}

/**
 * Sync progress update
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SyncProgressData (
  val phase: String,
  val progress: Double,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SyncProgressData {
      val phase = pigeonVar_list[0] as String
      val progress = pigeonVar_list[1] as Double
      val message = pigeonVar_list[2] as String?
      return SyncProgressData(phase, progress, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      phase,
      progress,
      message,
    )
  }
}
private open class AccountManagerApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SyncStatus.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AccountData.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SyncStatsData.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SyncResultData.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PeriodicSyncConfig.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AuthTokenResult.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SyncProgressData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SyncStatus -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is AccountData -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is SyncStatsData -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is SyncResultData -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PeriodicSyncConfig -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is AuthTokenResult -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is SyncProgressData -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AccountManagerHostApi {
  fun addAccount(account: AccountData, password: String, callback: (Result<Boolean>) -> Unit)
  fun getAccounts(accountType: String, callback: (Result<List<AccountData>>) -> Unit)
  fun getAccount(username: String, accountType: String, callback: (Result<AccountData?>) -> Unit)
  fun updateAccount(account: AccountData, callback: (Result<Boolean>) -> Unit)
  fun removeAccount(account: AccountData, callback: (Result<Boolean>) -> Unit)
  fun accountExists(username: String, accountType: String, callback: (Result<Boolean>) -> Unit)
  fun updateCredentials(account: AccountData, newPassword: String, callback: (Result<Boolean>) -> Unit)
  fun validateCredentials(username: String, password: String, accountType: String, callback: (Result<Boolean>) -> Unit)
  fun clearCredentials(account: AccountData, callback: (Result<Boolean>) -> Unit)
  fun getAuthToken(account: AccountData, tokenType: String, callback: (Result<AuthTokenResult>) -> Unit)
  fun setAuthToken(account: AccountData, tokenType: String, token: String, callback: (Result<Boolean>) -> Unit)
  fun invalidateAuthToken(accountType: String, token: String, callback: (Result<Boolean>) -> Unit)
  fun invalidateAllTokens(account: AccountData, tokenType: String, callback: (Result<Boolean>) -> Unit)
  fun getAvailableTokenTypes(account: AccountData, callback: (Result<List<String>>) -> Unit)
  fun syncNow(account: AccountData, expedited: Boolean, callback: (Result<SyncResultData>) -> Unit)
  fun setSyncAutomatically(account: AccountData, enabled: Boolean, callback: (Result<Boolean>) -> Unit)
  fun isSyncAutomatically(account: AccountData, callback: (Result<Boolean>) -> Unit)
  fun addPeriodicSync(account: AccountData, config: PeriodicSyncConfig, callback: (Result<Boolean>) -> Unit)
  fun removePeriodicSync(account: AccountData, callback: (Result<Boolean>) -> Unit)
  fun getSyncStatus(account: AccountData, callback: (Result<SyncStatus>) -> Unit)
  fun cancelSync(account: AccountData, callback: (Result<Boolean>) -> Unit)
  fun openAccountSettings(callback: (Result<Boolean>) -> Unit)
  fun isConfigured(callback: (Result<Boolean>) -> Unit)
  fun getPlatformCapabilities(callback: (Result<Map<String, Boolean>>) -> Unit)

  companion object {
    /** The codec used by AccountManagerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      AccountManagerApiPigeonCodec()
    }
    /** Sets up an instance of `AccountManagerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AccountManagerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.addAccount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            val passwordArg = args[1] as String
            api.addAccount(accountArg, passwordArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.getAccounts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountTypeArg = args[0] as String
            api.getAccounts(accountTypeArg) { result: Result<List<AccountData>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.getAccount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val usernameArg = args[0] as String
            val accountTypeArg = args[1] as String
            api.getAccount(usernameArg, accountTypeArg) { result: Result<AccountData?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.updateAccount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            api.updateAccount(accountArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.removeAccount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            api.removeAccount(accountArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.accountExists$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val usernameArg = args[0] as String
            val accountTypeArg = args[1] as String
            api.accountExists(usernameArg, accountTypeArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.updateCredentials$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            val newPasswordArg = args[1] as String
            api.updateCredentials(accountArg, newPasswordArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.validateCredentials$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val usernameArg = args[0] as String
            val passwordArg = args[1] as String
            val accountTypeArg = args[2] as String
            api.validateCredentials(usernameArg, passwordArg, accountTypeArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.clearCredentials$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            api.clearCredentials(accountArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.getAuthToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            val tokenTypeArg = args[1] as String
            api.getAuthToken(accountArg, tokenTypeArg) { result: Result<AuthTokenResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.setAuthToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            val tokenTypeArg = args[1] as String
            val tokenArg = args[2] as String
            api.setAuthToken(accountArg, tokenTypeArg, tokenArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.invalidateAuthToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountTypeArg = args[0] as String
            val tokenArg = args[1] as String
            api.invalidateAuthToken(accountTypeArg, tokenArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.invalidateAllTokens$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            val tokenTypeArg = args[1] as String
            api.invalidateAllTokens(accountArg, tokenTypeArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.getAvailableTokenTypes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            api.getAvailableTokenTypes(accountArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.syncNow$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            val expeditedArg = args[1] as Boolean
            api.syncNow(accountArg, expeditedArg) { result: Result<SyncResultData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.setSyncAutomatically$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            val enabledArg = args[1] as Boolean
            api.setSyncAutomatically(accountArg, enabledArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.isSyncAutomatically$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            api.isSyncAutomatically(accountArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.addPeriodicSync$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            val configArg = args[1] as PeriodicSyncConfig
            api.addPeriodicSync(accountArg, configArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.removePeriodicSync$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            api.removePeriodicSync(accountArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.getSyncStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            api.getSyncStatus(accountArg) { result: Result<SyncStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.cancelSync$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accountArg = args[0] as AccountData
            api.cancelSync(accountArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.openAccountSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.openAccountSettings{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.isConfigured$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isConfigured{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.account_manager.AccountManagerHostApi.getPlatformCapabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getPlatformCapabilities{ result: Result<Map<String, Boolean>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class SyncCallbackFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by SyncCallbackFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      AccountManagerApiPigeonCodec()
    }
  }
  fun onSyncStarted(accountArg: AccountData, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.account_manager.SyncCallbackFlutterApi.onSyncStarted$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(accountArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onSyncProgress(accountArg: AccountData, progressArg: SyncProgressData, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.account_manager.SyncCallbackFlutterApi.onSyncProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(accountArg, progressArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onSyncCompleted(accountArg: AccountData, resultArg: SyncResultData, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.account_manager.SyncCallbackFlutterApi.onSyncCompleted$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(accountArg, resultArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onSyncCancelled(accountArg: AccountData, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.account_manager.SyncCallbackFlutterApi.onSyncCancelled$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(accountArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onSyncConflict(accountArg: AccountData, conflictIdArg: String, localDataArg: String, remoteDataArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.account_manager.SyncCallbackFlutterApi.onSyncConflict$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(accountArg, conflictIdArg, localDataArg, remoteDataArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class AccountCallbackFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by AccountCallbackFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      AccountManagerApiPigeonCodec()
    }
  }
  fun onAccountAdded(accountArg: AccountData, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.account_manager.AccountCallbackFlutterApi.onAccountAdded$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(accountArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onAccountRemoved(accountArg: AccountData, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.account_manager.AccountCallbackFlutterApi.onAccountRemoved$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(accountArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onAccountUpdated(accountArg: AccountData, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.account_manager.AccountCallbackFlutterApi.onAccountUpdated$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(accountArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onAuthTokenExpired(accountArg: AccountData, tokenTypeArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.account_manager.AccountCallbackFlutterApi.onAuthTokenExpired$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(accountArg, tokenTypeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
